package com.caddie.app.accessibility

import android.os.SystemClock

/**
 * Tracks agent activity so CompanionAccessibilityService can attribute
 * an observed click: was it the agent or the human?
 *
 * - [consumeExpectedAgentClick] — consumes the single click expected from an agent action.
 * - [isRunLikelyActive] — long window; only during an active run should a touch count as intervention.
 */
object AgentActivityTracker {

    private const val GESTURE_MARGIN_MS = 2500L
    private const val SEMANTIC_CLICK_MARGIN_MS = 500L
    private const val RUN_ACTIVE_WINDOW_MS = 90_000L

    private val clickAttribution = AgentClickAttribution(SystemClock::uptimeMillis)

    @Volatile
    private var lastRunActivityMs: Long = 0L

    /** Call BEFORE every dispatchGesture. */
    fun markDispatch(durationMs: Int) {
        val now = SystemClock.uptimeMillis()
        clickAttribution.expectAgentClick(maxOf(0, durationMs) + GESTURE_MARGIN_MS)
        lastRunActivityMs = now
    }

    /** Marks a node click so its Accessibility event is not mistaken for a human touch. */
    fun markSemanticClick() {
        val now = SystemClock.uptimeMillis()
        clickAttribution.expectAgentClick(SEMANTIC_CLICK_MARGIN_MS)
        lastRunActivityMs = now
    }

    /** Returns true only for the next click generated by the marked agent action. */
    fun consumeExpectedAgentClick(): Boolean =
        clickAttribution.consumeExpectedAgentClick()

    /** Call at every agent request (keeps the run "active"). */
    fun markRunActivity() {
        lastRunActivityMs = SystemClock.uptimeMillis()
    }

    /** Call at task_finished — closes the run window immediately. */
    fun markRunFinished() {
        lastRunActivityMs = 0L
        clickAttribution.clear()
    }

    val isRunLikelyActive: Boolean
        get() = lastRunActivityMs > 0L &&
            SystemClock.uptimeMillis() - lastRunActivityMs < RUN_ACTIVE_WINDOW_MS
}

/** Attributes at most one near-term click event to a dispatched agent action. */
internal class AgentClickAttribution(
    private val nowMillis: () -> Long,
) {
    private var expected = false
    private var expectedUntilMs = 0L

    @Synchronized
    fun expectAgentClick(validForMs: Long) {
        expected = true
        expectedUntilMs = nowMillis() + maxOf(0L, validForMs)
    }

    @Synchronized
    fun consumeExpectedAgentClick(): Boolean {
        val attributedToAgent = expected && nowMillis() <= expectedUntilMs
        clear()
        return attributedToAgent
    }

    @Synchronized
    fun clear() {
        expected = false
        expectedUntilMs = 0L
    }
}
