DEFAULT_BACKEND = "adb"
DEFAULT_HTTP_BRIDGE_URL = "http://127.0.0.1:8765"
DEFAULT_AGENT_HOST = "0.0.0.0"
DEFAULT_AGENT_PORT = 8787
DEFAULT_LM_STUDIO_ENDPOINT = "http://127.0.0.1:1234/api/v1/chat"
DEFAULT_LM_STUDIO_MODEL = "qwen/qwen3.6-35b-a3b"
DEFAULT_LM_STUDIO_INTEGRATION = "mcp/llm-smartphone"
DEFAULT_LM_STUDIO_CONTEXT_LENGTH = 16000

ENV_BACKEND = "LLM_SMARTPHONE_BACKEND"
ENV_HTTP_BRIDGE_URL = "LLM_SMARTPHONE_HTTP_URL"
ENV_AGENT_HOST = "LLM_SMARTPHONE_AGENT_HOST"
ENV_AGENT_PORT = "LLM_SMARTPHONE_AGENT_PORT"
ENV_LM_STUDIO_ENDPOINT = "LLM_STUDIO_ENDPOINT"
ENV_LM_STUDIO_MODEL = "LLM_STUDIO_MODEL"
ENV_LM_STUDIO_INTEGRATION = "LLM_STUDIO_MCP_INTEGRATION"
ENV_LM_STUDIO_CONTEXT_LENGTH = "LLM_STUDIO_CONTEXT_LENGTH"
